### ISSUE TITLE
Foute berekening tpr bij forfait 

### ISSUE THREAD

**Issue by lambda-ai** [MaddensProgramming/interclub#1]
Dag Martijn,

Heel handige app, bedankt! Niet dat ik geobsedeerd ben door m'n eigen TPR of zo ;-)... maar er zit een foutje in de berekening: je neemt de score uiteraard niet mee, maar je gebruikt het elo van de tegenstander wel bij het berekenen van het gemiddelde. In mijn geval: en forfait winst tegen 1600 haalt het gemiddelde en dus de tpr met meer dan 100 naar beneden.

Mvg,
Mathias

**Comment by MaddensProgramming** [comment]
Hey Mathias, 

Merci om dat te vinden! Het is aangepast. 
Het probleem zat in mijn andere (nog minder goed georganiseerde) repo om de data in te lezen. (https://github.com/MaddensProgramming/InterclubPoging2/commit/be4537966c2c748cd53d9f5520fdd49e13915d5d)
Voor vorige jaren zal ik dan later wel nog eens een reload doen. 


Groeten Martijn
